# Generated by Django 4.0.2 on 2022-06-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_referenceno'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('general', 'GENERAL'), ('technology', 'TECHNOLOGY'), ('science', 'SCIENCE'), ('news', 'NEWS')], default='general', max_length=20),
        ),
    ]
